schema_version: 1

context:
  version: "0.11.0.post1"
  python_min: "3.12"

package:
  name: easydynamics
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/E/EasyDynamics/easydynamics-${{ version }}.tar.gz
  sha256: 5ed1b86437419a829029399fec28762d2502f33372eef176cd60f02d031bdef5

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - easyscience >=2.5.1
    - numpy
    - scipy
    - scipp
    - h5py
    - matplotlib-base
    - pooch
    - darkdetect
    - plopp
    - ipywidgets
    - ipympl
    - sympy

tests:
  - python:
      imports:
        - easydynamics
      pip_check: false
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: QENS data analysis
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/easyscience/dynamics-lib
  documentation: https://easyscience.github.io/dynamics-lib

extra:
  recipe-maintainers:
    - MridulS
